import PlayerAvatar from '../assets/player.jpg';

export const soccerData = {
  enfuego: {
    team_name: 'En Fuego CF',
    team_players: [
      {
        id: 'player-01',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-02',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-03',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-04',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-05',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-06',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-07',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-08',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-09',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-10',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-11',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
    ],
    team_performance: [],
    scheduled_matches: [],
    upcoming_matches: [
      {
        id: 'upcoming-match-01',
        opponent: 'Rush Hour',
        date: 'Wed, 7 September',
        time: '04:00 PM',
        venue: 'Abcvs ayt',
      },
      {
        id: 'upcoming-match-02',
        opponent: 'Hooligans FC',
        date: 'Fri, 9 September',
        time: '07:00 PM',
        venue: 'Abcvs ayt',
      },
      {
        id: 'upcoming-match-03',
        opponent: 'Inter Real Hustlers FC',
        date: 'Sun, 11 September',
        time: '04:00 PM',
        venue: 'Abcvs ayt',
      },
      {
        id: 'upcoming-match-04',
        opponent: 'Real Hustlers',
        date: 'Tue, 13 September',
        time: '04:00 PM',
        venue: 'Abcvs ayt',
      },
      {
        id: 'upcoming-match-05',
        opponent: 'Avengars',
        date: 'Thu, 15 September',
        time: '04:00 PM',
        venue: 'Abcvs ayt',
      },
      {
        id: 'upcoming-match-06',
        opponent: 'Amigos',
        date: 'Sat, 17 September',
        time: '04:00 PM',
        venue: 'Abcvs ayt',
      },
      {
        id: 'upcoming-match-06',
        opponent: 'Thunder',
        date: 'Mon, 17 September',
        time: '04:00 PM',
        venue: 'Abcvs ayt',
      },
    ],
  },

  rush_hour: {
    team_name: 'Rush Hour',
    team_players: [
      {
        id: 'player-01',
        player_name: 'Ronaldo',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-02',
        player_name: 'Ronaldo',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-03',
        player_name: 'Ronaldo',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-04',
        player_name: 'Ronaldo',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-05',
        player_name: 'Ronaldo',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-06',
        player_name: 'Ronaldo',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-07',
        player_name: 'Ronaldo',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-08',
        player_name: 'Ronaldo',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-09',
        player_name: 'Ronaldo',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-10',
        player_name: 'Ronaldo',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-11',
        player_name: 'Ronaldo',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
    ],
    team_performance: [],
    scheduled_matches: [],
    upcoming_matches: [
      {
        id: 'upcoming-match-01',
        opponent: 'En Fuego CF',
        date: 'Wed, 7 September',
        time: '04:00 PM',
        venue: 'Abcvs ayt',
      },
      {
        id: 'upcoming-match-02',
        opponent: 'Hooligans FC',
        date: 'Fri, 9 September',
        time: '07:00 PM',
        venue: 'Abcvs ayt',
      },
      {
        id: 'upcoming-match-03',
        opponent: 'Inter Real Hustlers FC',
        date: 'Sun, 11 September',
        time: '04:00 PM',
        venue: 'Abcvs ayt',
      },
      {
        id: 'upcoming-match-04',
        opponent: 'Real Hustlers',
        date: 'Tue, 13 September',
        time: '04:00 PM',
        venue: 'Abcvs ayt',
      },
      {
        id: 'upcoming-match-05',
        opponent: 'Avengars',
        date: 'Thu, 15 September',
        time: '04:00 PM',
        venue: 'Abcvs ayt',
      },
      {
        id: 'upcoming-match-06',
        opponent: 'Amigos',
        date: 'Sat, 17 September',
        time: '04:00 PM',
        venue: 'Abcvs ayt',
      },
      {
        id: 'upcoming-match-06',
        opponent: 'Thunder',
        date: 'Mon, 17 September',
        time: '04:00 PM',
        venue: 'Abcvs ayt',
      },
    ],
  },

  hooligans_FC: {
    team_name: 'Hooligans FC',
    team_players: [
      {
        id: 'player-01',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-02',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-03',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-04',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-05',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-06',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-07',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-08',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-09',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-10',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-11',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
    ],
    team_performance: [],
    scheduled_matches: [],
    upcoming_matches: [
      {
        id: 'upcoming-match-01',
        opponent: 'En Fuego CF',
        date: 'Wed, 7 September',
        time: '04:00 PM',
        venue: 'Abcvs ayt',
      },
      {
        id: 'upcoming-match-02',
        opponent: 'Rush Hour',
        date: 'Fri, 9 September',
        time: '07:00 PM',
        venue: 'Abcvs ayt',
      },
      {
        id: 'upcoming-match-03',
        opponent: 'Inter Real Hustlers FC',
        date: 'Sun, 11 September',
        time: '04:00 PM',
        venue: 'Abcvs ayt',
      },
      {
        id: 'upcoming-match-04',
        opponent: 'Real Hustlers',
        date: 'Tue, 13 September',
        time: '04:00 PM',
        venue: 'Abcvs ayt',
      },
      {
        id: 'upcoming-match-05',
        opponent: 'Avengars',
        date: 'Thu, 15 September',
        time: '04:00 PM',
        venue: 'Abcvs ayt',
      },
      {
        id: 'upcoming-match-06',
        opponent: 'Amigos',
        date: 'Sat, 17 September',
        time: '04:00 PM',
        venue: 'Abcvs ayt',
      },
      {
        id: 'upcoming-match-06',
        opponent: 'Thunder',
        date: 'Mon, 17 September',
        time: '04:00 PM',
        venue: 'Abcvs ayt',
      },
    ],
  },

  real_hustlers: {
    team_name: 'Inter Real Hustlers FC',
    team_players: [
      {
        id: 'player-01',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-02',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-03',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-04',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-05',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-06',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-07',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-08',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-09',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-10',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-11',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
    ],
    team_performance: [],
    scheduled_matches: [],
    upcoming_matches: [
      {
        id: 'upcoming-match-01',
        opponent: 'En Fuego CF',
        date: 'Wed, 7 September',
        time: '04:00 PM',
        venue: 'Abcvs ayt',
      },
      {
        id: 'upcoming-match-02',
        opponent: 'Hooligans FC',
        date: 'Fri, 9 September',
        time: '07:00 PM',
        venue: 'Abcvs ayt',
      },
      {
        id: 'upcoming-match-03',
        opponent: 'Inter Real Hustlers FC',
        date: 'Sun, 11 September',
        time: '04:00 PM',
        venue: 'Abcvs ayt',
      },
      {
        id: 'upcoming-match-04',
        opponent: 'Rush Hours',
        date: 'Tue, 13 September',
        time: '04:00 PM',
        venue: 'Abcvs ayt',
      },
      {
        id: 'upcoming-match-05',
        opponent: 'Avengars',
        date: 'Thu, 15 September',
        time: '04:00 PM',
        venue: 'Abcvs ayt',
      },
      {
        id: 'upcoming-match-06',
        opponent: 'Amigos',
        date: 'Sat, 17 September',
        time: '04:00 PM',
        venue: 'Abcvs ayt',
      },
      {
        id: 'upcoming-match-06',
        opponent: 'Thunder',
        date: 'Mon, 17 September',
        time: '04:00 PM',
        venue: 'Abcvs ayt',
      },
    ],
  },

  avengars: {
    team_name: 'Team Avengers',
    team_players: [
      {
        id: 'player-01',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-02',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-03',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-04',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-05',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-06',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-07',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-08',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-09',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-10',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-11',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
    ],
    team_performance: [],
    scheduled_matches: [],
    upcoming_matches: [
      {
        id: 'upcoming-match-01',
        opponent: 'En Fuego CF',
        date: 'Wed, 7 September',
        time: '04:00 PM',
        venue: 'Abcvs ayt',
      },
      {
        id: 'upcoming-match-06',
        opponent: 'Thunder',
        date: 'Mon, 17 September',
        time: '04:00 PM',
        venue: 'Abcvs ayt',
      },
      {
        id: 'upcoming-match-02',
        opponent: 'Hooligans FC',
        date: 'Fri, 9 September',
        time: '07:00 PM',
        venue: 'Abcvs ayt',
      },
      {
        id: 'upcoming-match-03',
        opponent: 'Inter Real Hustlers FC',
        date: 'Sun, 11 September',
        time: '04:00 PM',
        venue: 'Abcvs ayt',
      },
      {
        id: 'upcoming-match-04',
        opponent: 'Real Hustlers',
        date: 'Tue, 13 September',
        time: '04:00 PM',
        venue: 'Abcvs ayt',
      },
      {
        id: 'upcoming-match-05',
        opponent: 'Rush Hour',
        date: 'Thu, 15 September',
        time: '04:00 PM',
        venue: 'Abcvs ayt',
      },
      {
        id: 'upcoming-match-06',
        opponent: 'Amigos',
        date: 'Sat, 17 September',
        time: '04:00 PM',
        venue: 'Abcvs ayt',
      },
    ],
  },

  amigos: {
    team_name: 'Amigos',
    team_players: [
      {
        id: 'player-01',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-02',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-03',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-04',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-05',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-06',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-07',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-08',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-09',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-10',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-11',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
    ],
    team_performance: [],
    scheduled_matches: [],
    upcoming_matches: [
      {
        id: 'upcoming-match-01',
        opponent: 'En Fuego CF',
        date: 'Wed, 7 September',
        time: '04:00 PM',
        venue: 'Abcvs ayt',
      },
      {
        id: 'upcoming-match-06',
        opponent: 'Thunder',
        date: 'Mon, 17 September',
        time: '04:00 PM',
        venue: 'Abcvs ayt',
      },
      {
        id: 'upcoming-match-02',
        opponent: 'Hooligans FC',
        date: 'Fri, 9 September',
        time: '07:00 PM',
        venue: 'Abcvs ayt',
      },
      {
        id: 'upcoming-match-03',
        opponent: 'Inter Real Hustlers FC',
        date: 'Sun, 11 September',
        time: '04:00 PM',
        venue: 'Abcvs ayt',
      },
      {
        id: 'upcoming-match-04',
        opponent: 'Real Hustlers',
        date: 'Tue, 13 September',
        time: '04:00 PM',
        venue: 'Abcvs ayt',
      },
      {
        id: 'upcoming-match-05',
        opponent: 'Avengars',
        date: 'Thu, 15 September',
        time: '04:00 PM',
        venue: 'Abcvs ayt',
      },
      {
        id: 'upcoming-match-06',
        opponent: 'Rush Hour',
        date: 'Sat, 17 September',
        time: '04:00 PM',
        venue: 'Abcvs ayt',
      },
    ],
  },

  thunder: {
    team_name: 'Thunder',
    team_players: [
      {
        id: 'player-01',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-02',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-03',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-04',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-05',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-06',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-07',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-08',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-09',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-10',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
      {
        id: 'player-11',
        player_name: 'Marcel',
        apperances: '21',
        avatar: PlayerAvatar,
        goals: '3',
        assists: '5',
        cross_accuracy: '36',
        key_passes: '2',
        tackles: '1.9',
      },
    ],
    team_performance: [],
    scheduled_matches: [],
    upcoming_matches: [
      {
        id: 'upcoming-match-01',
        opponent: 'En Fuego CF',
        date: 'Wed, 7 September',
        time: '04:00 PM',
        venue: 'Abcvs ayt',
      },
      {
        id: 'upcoming-match-02',
        opponent: 'Hooligans FC',
        date: 'Fri, 9 September',
        time: '07:00 PM',
        venue: 'Abcvs ayt',
      },
      {
        id: 'upcoming-match-03',
        opponent: 'Inter Real Hustlers FC',
        date: 'Sun, 11 September',
        time: '04:00 PM',
        venue: 'Abcvs ayt',
      },
      {
        id: 'upcoming-match-04',
        opponent: 'Real Hustlers',
        date: 'Tue, 13 September',
        time: '04:00 PM',
        venue: 'Abcvs ayt',
      },
      {
        id: 'upcoming-match-05',
        opponent: 'Avengars',
        date: 'Thu, 15 September',
        time: '04:00 PM',
        venue: 'Abcvs ayt',
      },
      {
        id: 'upcoming-match-06',
        opponent: 'Amigos',
        date: 'Sat, 17 September',
        time: '04:00 PM',
        venue: 'Abcvs ayt',
      },
    ],
  },
};

export const teamData = Object.entries(soccerData).map(([_, value]) => value);
